grid = [
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
]

gridA = [
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
]

gridA2 = [
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', 'C', 'C', 'C', 'C', 'C', 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', 'C', 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', 'C', 'C', 'C', 'C', 'C', 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
]

gridB = [
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', 'N', 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', 'N', 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', None, 'C', 'N', 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', 'N', 'N', 'N', 'N', 'N', 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', None, 'C', None, 'C', 'N', 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', None, 'C', None, 'C', 'N', 'C', None, 'C'],
  [None, 'N', 'N', 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', 'N', 'C', None, 'C', None, 'C', None, 'C', 'N', 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', 'N', 'N', None],
  ['C', 'N', 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
]

gridB2 = [
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', 'N', 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', 'N', 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', None, 'C', 'N', 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', 'N', 'N', 'N', 'N', 'N', 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', None, 'C', None, 'C', 'N', 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', 'N', 'C', None, 'C', None, 'C', 'N', 'C', None, 'C'],
  [None, 'N', 'N', 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', 'N', 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', 'N', 'N', None],
  ['C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C', None, 'C'],
  [None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None, 'N', None],
]